packages:
  - 'autobackup'
  - 'blueprints/aws-workspaces'
  - 'cdk'
  - '!**/cdk.out/**'
  - '!**/dist/**'
catalog:
  "@aws-cdk/aws-lambda-go-alpha": "^2.256.0-alpha.0"
  "@aws-cdk/aws-lambda-python-alpha": "^2.256.0-alpha.0"
  "@aws-cdk/aws-redshift-alpha": "^2.256.0-alpha.0"
  "@aws-sdk/client-dynamodb": "^3.996.2"
  "@aws-sdk/client-elastic-load-balancing-v2": "^3.996.2"
  "@aws-sdk/credential-provider-node": "^3.972.43"
  "@aws-sdk/util-dynamodb": "^3.996.2"
  "@biomejs/biome": "2.4.5"
  "@changesets/cli": "^2.31.0"
  "@opensearch-project/opensearch": "^2.13.0"
  "@types/node": "^24.1.0"
  "aws-cdk": "2.1124.0"
  "aws-cdk-lib": "2.256.0"
  "cdk-monitoring-constructs": "10.0.0"
  "constructs": "^10.6.0"
  "esbuild": "^0.28.0"
  "ts-node": "^10.9.2"
  "tsx": "4.22.3"
  "typescript": "~5.9.3"
  "vitest": "4.1.7"
